name: Feature request
description: Suggest an improvement
title: "feat: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
  - type: checkboxes
    id: help
    attributes:
      label: Are you able to help?
      options:
        - label: I would be willing to open a pull request for this
