import path from "path";
import fs from "fs";
import { promisify } from "util";
import { CoverageData } from "../../getCoverage";
import { generateSummaryPage } from "./pages/summary";
import { generateDetailsPage } from "./pages/details";
import { escapeHTML, relativeToRoot, toURLPath } from "./escape";
import {
  CODEMIRROR_CSS,
  CODEMIRROR_JAVASCRIPT_MODE_JS,
  CODEMIRROR_JS,
  ExternalAsset,
  SEMANTIC_UI_CSS,
  SORTTABLE_JS,
  isExternalAsset
} from "./assets";

const writeFile = promisify(fs.writeFile);
const readFile = promisify(fs.readFile);
const mkdir = promisify(fs.mkdir);

export type Options = {
  outputDir: string;
  threshold: number;
  // NOTE: Injectable so the output is deterministic. Embedding new Date()
  // directly made every full-page snapshot flaky and churned the committed
  // docs/ demo on every regeneration.
  generatedAt?: Date;
};

const checkOrWriteFolder = (outputDir: string): string => {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
  }

  return outputDir;
};

const includeAsset = (asset: string | ExternalAsset): string => {
  const url = isExternalAsset(asset) ? asset.url : asset;
  // Third-party assets are pinned by hash; local ones are copied from this
  // package and have nothing to verify against.
  const integrity = isExternalAsset(asset)
    ? ` integrity="${asset.integrity}" crossorigin="anonymous" referrerpolicy="no-referrer"`
    : "";
  const extension = path.extname(new URL(url, "file:///").pathname);

  if (extension === ".js") {
    return `<script src="${url}" type="text/javascript" charset="utf-8"${integrity}></script>`;
  }

  if (extension === ".css") {
    return `<link href="${url}" type="text/css" rel="stylesheet"${integrity}>`;
  }

  console.warn(`includeAsset: couldn't recognise the extension ${extension}`);

  return "";
};

const includeAssets = (assets: readonly (string | ExternalAsset)[]): string =>
  assets.map(includeAsset).join("\n");

const wrapHTMLContent = (
  // TODO: replace this untyped seam with a typed layout() helper.
  // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
  renderFn: Function,
  props?: Record<string, any>,
  options:
    | {
        title?: string;
        assets?: string;
        generatedAt?: Date;
      }
    | undefined = {}
): string => {
  const content = renderFn(props);

  return `
  <!DOCTYPE html>
  <html>
    <head>
      <title>${escapeHTML(options.title || "TypeScript coverage report")}</title>
      ${includeAsset(SEMANTIC_UI_CSS)}
      ${options.assets || ""}
    </head>
    <body>
    ${content}
    <p class="footer-text">TypeScript Coverage Report generated by <a href="https://github.com/plantain-00/type-coverage">type-coverage</a> and <a href="https://github.com/alexcanessa/typescript-coverage-report">typescript-coverage-report</a> at ${(options.generatedAt ?? new Date()).toUTCString()}</p>
    </body>
  </html>
  `;
};

// NOTE: This generate function has side effect of creating the index.html
export const generate = async (
  data: CoverageData,
  options: Options
): Promise<void> => {
  // NOTE: Create index file
  const fileContent = wrapHTMLContent(
    generateSummaryPage,
    {
      fileCounts: data.fileCounts,
      percentage: data.percentage,
      total: data.total,
      covered: data.covered,
      uncovered: data.uncovered,
      threshold: options.threshold
    },
    {
      assets: includeAssets(["./assets/report.css", SORTTABLE_JS])
    }
  );

  await writeFile(
    path.join(checkOrWriteFolder(options.outputDir), "index.html"),
    fileContent
  );

  // NOTE: Create the other files
  for (const [filename, { totalCount, correctCount }] of Array.from(
    data.fileCounts
  )) {
    await mkdir(path.join(options.outputDir, "files", path.dirname(filename)), {
      recursive: true
    });

    const annotations = data.anys.filter(({ file }) => file === filename);
    const assetsFolder = `${relativeToRoot(filename)}assets`;

    // NOTE: A file listed by the type checker may not be readable by the time
    // we get here. Degrade to skipping its detail page rather than aborting
    // the whole run with exit code 255, which is what #140 reported.
    let sourceCode: string;
    try {
      sourceCode = await readFile(filename, "utf-8");
    } catch (error) {
      console.warn(
        `Skipping detail page for ${filename}: ${(error as Error).message}`
      );
      continue;
    }
    const detailContent = wrapHTMLContent(
      generateDetailsPage,
      {
        filename,
        sourceCode,
        totalCount,
        correctCount,
        annotations,
        threshold: options.threshold
      },
      {
        title: path.basename(filename),
        assets: includeAssets([
          CODEMIRROR_JS,
          CODEMIRROR_JAVASCRIPT_MODE_JS,
          CODEMIRROR_CSS,
          toURLPath(`${assetsFolder}/report.css`),
          toURLPath(`${assetsFolder}/source-file.js`)
        ])
      }
    );

    await writeFile(
      path.join(options.outputDir, "files", `${filename}.html`),
      detailContent
    );
  }

  const generatedFile = path.resolve(
    path.join(options.outputDir, "index.html")
  );

  console.log(`View generated HTML Report at ${generatedFile}`);
};
